import os
import json
from glob import glob

HEADER = ('## {id} - {name}\n'
          '<!-- THIS FILE IS AUTOGENERATED. DO NOT EDIT. -->\n\n')

ENTRY = '[**{type}{title}**]({link}){author}{comment}\n\n'

TYPE = '{type}: '

AUTHOR = ': *{author}*'

COMMENT = ' ({comment})'


def format_type(type_):
    if type_:
        return TYPE.format(type=type_)
    return ''


def format_author(author):
    if author:
        return AUTHOR.format(type=author)
    return ''


def format_comment(comment):
    if comment:
        return COMMENT.format(comment=comment)
    return ''


def format_entry(entry):
    type_ = format_type(entry.get('type', ''))
    author = format_author(entry.get('author', ''))
    comment = format_comment(entry.get('comment', ''))

    try:
        return ENTRY.format(
            type=type_,
            title=entry['title'],
            link=entry['link'],
            author=author,
            comment=comment,
        )
    except KeyError:
        raise KeyError('entry missing mandatory information (title or link)')


def format_header(data):
    try:
        return HEADER.format(
            id=data['id'],
            name=data['name'],
        )
    except KeyError:
        raise KeyError('header missing mandatory information (id or name)')


def format_md(data):
    header = format_header(data)

    return header + ''.join([format_entry(entry) for entry in data['entries']])


def json_to_md_filename(json_path):
    split = os.path.split(json_path)

    return os.path.join(split[0], (os.path.splitext(split[1])[0] + '.md'))


def json_to_md(json_path):
    md_path = json_to_md_filename(json_path)

    with open(json_path) as json_file:
        data = json.load(json_file)

    md_data = format_md(data)

    with open(md_path, 'w') as md_file:
        md_file.write(md_data)


json_to_md('/home/caio/Documents/UFSC/Calico/biblioteca/1a_fase/Calculo-A.json')


# for path in glob('*/*.md'):
#     if os.stat(path).st_size == 0:
#         os.rename(path, to_json(path))
